### ISSUE TITLE
Listing position on sm screen

### ISSUE THREAD

**Issue by Arrathilar** [Andriy125/dimonline#8]
На малих розширеннях таблиця поїхала вправо
![image](https://user-images.githubusercontent.com/20456330/79198250-df22ee00-7e3b-11ea-9927-070caad95f42.png)

**Comment by Andriy125** [comment]
Тут горизонтальний скролінг

**Comment by Arrathilar** [comment]
я мав на увазі те що сам блок таблиці(той що з заокругленими бордерами) виїхав за екран, зі скролінгом там все гуд
